[package]
name = "time-tracker"
version = "0.1.0"
description = "Local-first desktop time tracker"
authors = ["Chris Van"]
edition = "2021"

[lib]
name = "time_tracker_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = ["tray-icon"] }
tauri-plugin-sql = { version = "2", features = ["sqlite"] }
tauri-plugin-dialog = "2"
tauri-plugin-fs = "2"
tauri-plugin-notification = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
sysinfo = "0.39.6"
tauri-plugin-single-instance = "2"

[target."cfg(windows)".dependencies]
winreg = "0.56.0"
